/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gnei64Xtnzg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"

export function navbar() {
  return (
    <header className="w-full bg-white shadow-sm dark:bg-gray-950">
      <div className="container flex h-16 items-center justify-between px-4 md:px-6">
        <Link className="flex items-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="ml-2 text-lg font-medium">Acme Inc</span>
        </Link>
        <nav className="hidden lg:flex items-center space-x-6">
          <Link className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50" href="#">
            Home
          </Link>
          <Link className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50" href="#">
            About Us
          </Link>
          <Link className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50" href="#">
            Services
          </Link>
          <Link className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50" href="#">
            Projects
          </Link>
          <Link className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50" href="#">
            Portfolio
          </Link>
        </nav>
        <Link
          className="hidden lg:inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
          href="#"
        >
          Contact
        </Link>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="lg:hidden" size="icon" variant="outline">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <div className="grid gap-4 p-6">
              <Link
                className="flex items-center text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Home
              </Link>
              <Link
                className="flex items-center text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                About Us
              </Link>
              <Link
                className="flex items-center text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Services
              </Link>
              <Link
                className="flex items-center text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Projects
              </Link>
              <Link
                className="flex items-center text-sm font-medium hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Portfolio
              </Link>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Contact
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </div>
    </header>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
